// Generated by gencpp from file hms_client/hms_msg.msg
// DO NOT EDIT!


#ifndef HMS_CLIENT_MESSAGE_HMS_MSG_H
#define HMS_CLIENT_MESSAGE_HMS_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hms_client
{
template <class ContainerAllocator>
struct hms_msg_
{
  typedef hms_msg_<ContainerAllocator> Type;

  hms_msg_()
    : header()
    , temp1()
    , temp2(0.0)  {
    }
  hms_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temp1(_alloc)
    , temp2(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _temp1_type;
  _temp1_type temp1;

   typedef float _temp2_type;
  _temp2_type temp2;





  typedef boost::shared_ptr< ::hms_client::hms_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hms_client::hms_msg_<ContainerAllocator> const> ConstPtr;

}; // struct hms_msg_

typedef ::hms_client::hms_msg_<std::allocator<void> > hms_msg;

typedef boost::shared_ptr< ::hms_client::hms_msg > hms_msgPtr;
typedef boost::shared_ptr< ::hms_client::hms_msg const> hms_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hms_client::hms_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hms_client::hms_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hms_client::hms_msg_<ContainerAllocator1> & lhs, const ::hms_client::hms_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.temp1 == rhs.temp1 &&
    lhs.temp2 == rhs.temp2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hms_client::hms_msg_<ContainerAllocator1> & lhs, const ::hms_client::hms_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hms_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hms_client::hms_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hms_client::hms_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hms_client::hms_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hms_client::hms_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hms_client::hms_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hms_client::hms_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hms_client::hms_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64608a45b1add361d21d3cecf93db1f6";
  }

  static const char* value(const ::hms_client::hms_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64608a45b1add361ULL;
  static const uint64_t static_value2 = 0xd21d3cecf93db1f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::hms_client::hms_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hms_client/hms_msg";
  }

  static const char* value(const ::hms_client::hms_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hms_client::hms_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string temp1\n"
"float32 temp2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hms_client::hms_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hms_client::hms_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temp1);
      stream.next(m.temp2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hms_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hms_client::hms_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hms_client::hms_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temp1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.temp1);
    s << indent << "temp2: ";
    Printer<float>::stream(s, indent + "  ", v.temp2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HMS_CLIENT_MESSAGE_HMS_MSG_H
