// Generated by gencpp from file hms_client/ping_pong.msg
// DO NOT EDIT!


#ifndef HMS_CLIENT_MESSAGE_PING_PONG_H
#define HMS_CLIENT_MESSAGE_PING_PONG_H

#include <ros/service_traits.h>


#include <hms_client/ping_pongRequest.h>
#include <hms_client/ping_pongResponse.h>


namespace hms_client
{

struct ping_pong
{

typedef ping_pongRequest Request;
typedef ping_pongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ping_pong
} // namespace hms_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hms_client::ping_pong > {
  static const char* value()
  {
    return "f8a6e80cda99ecae7bfeb48f745404ba";
  }

  static const char* value(const ::hms_client::ping_pong&) { return value(); }
};

template<>
struct DataType< ::hms_client::ping_pong > {
  static const char* value()
  {
    return "hms_client/ping_pong";
  }

  static const char* value(const ::hms_client::ping_pong&) { return value(); }
};


// service_traits::MD5Sum< ::hms_client::ping_pongRequest> should match
// service_traits::MD5Sum< ::hms_client::ping_pong >
template<>
struct MD5Sum< ::hms_client::ping_pongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hms_client::ping_pong >::value();
  }
  static const char* value(const ::hms_client::ping_pongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hms_client::ping_pongRequest> should match
// service_traits::DataType< ::hms_client::ping_pong >
template<>
struct DataType< ::hms_client::ping_pongRequest>
{
  static const char* value()
  {
    return DataType< ::hms_client::ping_pong >::value();
  }
  static const char* value(const ::hms_client::ping_pongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hms_client::ping_pongResponse> should match
// service_traits::MD5Sum< ::hms_client::ping_pong >
template<>
struct MD5Sum< ::hms_client::ping_pongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hms_client::ping_pong >::value();
  }
  static const char* value(const ::hms_client::ping_pongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hms_client::ping_pongResponse> should match
// service_traits::DataType< ::hms_client::ping_pong >
template<>
struct DataType< ::hms_client::ping_pongResponse>
{
  static const char* value()
  {
    return DataType< ::hms_client::ping_pong >::value();
  }
  static const char* value(const ::hms_client::ping_pongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HMS_CLIENT_MESSAGE_PING_PONG_H
